---
## Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v1.3.3-40-g014ab0f
_src_path: /Users/kamontat/Desktop/Personal/asdf-plugin-template
app_desc: A command-line tool that makes git easier to use with GitHub.
app_name: hub
app_repo: https://github.com/github/hub
app_website: https://hub.github.com
archive_conf_path: ''
archive_conf_strip: 1
archive_enabled: true
archive_regex: (\.tar\.gz|\.tgz|\.zip)$
checksum_enabled: false
custom_arch_enabled: true
custom_arch_yaml:
    aarch64*: arm64
    armv5*: arm
    armv6*: arm
    armv7*: arm
    x86_64: amd64
custom_bin_paths: bin
custom_non_stable_version: (-src|-dev|-latest|-stm|[-\.]rc|-alpha|-beta|[-\.]pre|-next|snapshot|master)
custom_os_enabled: false
custom_require_commands: ''
download_url: https://github.com/github/hub/releases/download/v{version}/hub-{os}-{arch}-{version}.tgz
gpg_enabled: false
install_map_enabled: false
package_enabled: false
plugin_author: Kamontat Chantrachirathumrong
plugin_name: asdf-hub
plugin_org: kc-workspace
plugin_repo: https://github.com/kc-workspace/asdf-hub.git
source_enabled: false
test_cmd_args: --version
version_file_enabled: false
version_prefix: v
