---
## Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v1.3.3
_src_path: gh:kc-workspace/asdf-plugin-template.git
app_download_file: hub
app_download_link: https://github.com/GrantBirki/hub/releases/download/v${version}/hub-${os}-${arch}-${version}.tgz
app_download_type: directory
app_git_repo: https://github.com/GrantBirki/hub
app_name: hub
app_strip_component: 1
git_remote: https://github.com/kc-workspace/asdf-hub.git
plugin_author: Kamontat Chantrachirathumrong
plugin_name: asdf-hub
plugin_org: kc-workspace
setting_os_mapper_darwin: darwin
setting_os_mapper_linux: linux
setting_test_command_arguments: --version
settings_os_mapper_enabled: false
